"""
National team tactical styles — injected into every player's decision prompt.

Each style defines:
  - philosophy : one-line identity
  - shoot_rule  : when to pull the trigger
  - pass_rule   : how to move the ball
  - press_rule  : defensive / pressing shape
  - width_rule  : how to use the flanks
  - set_pieces  : corner / free-kick approach
"""

TACTICAL_STYLES: dict[str, dict[str, str]] = {
    "Argentina": {
        "philosophy": "Win through individual brilliance and tight combinations. Every attack ends in a shot.",
        "shoot_rule": "Shoot from inside 25m without hesitation. If Messi or a CAM has the ball in the final third — shoot or play the killer pass, nothing else.",
        "pass_rule": "Short, sharp passes through the middle to unlock the defense. Never pass backward more than once in a row — always look to play forward.",
        "press_rule": "Press immediately when the ball is lost. Flood the ball-side to win it back within 5 seconds.",
        "width_rule": "Use wingers to stretch the defense wide, then cut inside or cross low for the striker.",
        "set_pieces": "Deliver to the back post. Runner from deep for a late header or cutback to the penalty spot.",
    },
    "Brazil": {
        "philosophy": "Attack with joy — dribble, skill, pace. The flanks are weapons. Score beautiful goals.",
        "shoot_rule": "Shoot early and often inside the box. Trust your technique. If you beat a defender, shoot before they recover.",
        "pass_rule": "One-touch combinations near the box. Vinicius and Rodrygo should always be looking to dribble first, pass second.",
        "press_rule": "High press as a unit. Win the ball in the opponent's half and immediately transition to attack.",
        "width_rule": "Vinicius and Rodrygo dominate the wings. Get them the ball in space and let them run at defenders.",
        "set_pieces": "Whipped cross to the six-yard box. Runners at near and far post.",
    },
    "France": {
        "philosophy": "Defensive solidity first. Win the ball then explode forward on the counter through Mbappé.",
        "shoot_rule": "Mbappé shoots on sight inside 30m. Other forwards shoot inside 20m. Midfielders shoot from range only if completely clear.",
        "pass_rule": "Quick vertical passes to release Mbappé in behind the defense. One or two passes max on the counter — do not slow it down.",
        "press_rule": "Sit in a compact mid-block, then counter the moment possession is won. Do not over-commit forward.",
        "width_rule": "Mbappé runs the left channel in behind. Right side feeds crosses into the box.",
        "set_pieces": "Giroud / Upamecano type — near-post attack with a second runner at the back post.",
    },
    "Czechia": {
        "philosophy": "Compact, organised and physical. Defend in a solid block, then attack directly through Souček's runs and balls into Schick.",
        "shoot_rule": "Schick shoots inside 18m on first sight. Souček shoots on any loose ball in the box. Provod/Barák shoot from 20-25m when stepping forward.",
        "pass_rule": "Get the ball forward quickly to Schick or in behind for the wingers. Avoid slow sideways build-up; release the overlapping full-back when blocked.",
        "press_rule": "Mid-block that springs into an aggressive press when the ball enters the middle third. Kuchta and Hložek lead the press from the front.",
        "width_rule": "Coufal and Jurásek overlap to deliver crosses. Černý cuts inside from the right onto his left foot.",
        "set_pieces": "Inswinging delivery to the near post for Souček or Schick; a tall second runner (Chorý/Krejčí) at the back post.",
    },
    "Paraguay": {
        "philosophy": "Pragmatic and defensively solid under Alfaro. Sit compact, stay organised, and hurt teams on the counter through Almirón and Enciso; a serious set-piece threat via Gustavo Gómez.",
        "shoot_rule": "Sanabria shoots inside 18m. Enciso and Almirón shoot from 20-25m when they cut inside. Don't force low-percentage efforts.",
        "pass_rule": "Win the ball then break quickly — vertical balls to release Almirón and Sosa in behind. Keep it tight and simple in your own half.",
        "press_rule": "Compact mid/low block; press in bursts when the ball enters the middle third rather than chasing high.",
        "width_rule": "Cáceres and Maidana support the wide men; Almirón drifts in off the right, Sosa stays wide left.",
        "set_pieces": "Inswinging deliveries to Gustavo Gómez and Balbuena — a primary route to goal given their aerial power.",
    },
    "England": {
        "philosophy": "Direct, physical football. Get the ball wide and deliver into the box for Kane.",
        "shoot_rule": "Kane shoots inside 20m on first touch. Bellingham shoots from 18-25m if stepping forward. Wingers shoot if they cut inside.",
        "pass_rule": "Direct ball over the top to Kane or in behind for Saka. Avoid unnecessary sideways passing — move it forward.",
        "press_rule": "Aggressive press in the opponent's half. Saka and Bellingham press the ball-carrier immediately.",
        "width_rule": "Saka drives at the left back. Trippier overlaps on the right and delivers early crosses.",
        "set_pieces": "Inswinging cross to Kane at the near post. Second runner at far post for a header back across goal.",
    },
    "Germany": {
        "philosophy": "Structured, disciplined, vertical football. Press, win, and attack at pace through organized channels.",
        "shoot_rule": "Shoot from outside the box if a clear lane opens — German players are clinical from range. Inside the box shoot immediately.",
        "pass_rule": "Quick combination through the lines — no more than 3 passes before a shot attempt or run in behind.",
        "press_rule": "Gegenpressing — the entire team presses immediately on losing the ball. Win it back in the middle third.",
        "width_rule": "Fullbacks push high. Wingers cut inside to shoot. Overlapping fullback delivers the cross.",
        "set_pieces": "Short corner into the channel, then a low, driven cross to the six-yard box.",
    },
    "Spain": {
        "philosophy": "Tiki-taka — keep the ball, create overloads, be patient until the gap opens then exploit it ruthlessly.",
        "shoot_rule": "Only shoot when the angle is clear inside 20m, or when a runner arrives late into the box. Do not rush — the next pass might be better.",
        "pass_rule": "Short passes to maintain possession and draw defenders out of shape. Switch play when overloaded. The final pass into the box must be incisive.",
        "press_rule": "Immediate press after losing possession — recover the ball before the opponent settles. All 10 outfield players press.",
        "width_rule": "Fullbacks Carvajal and Alba overlap to create 2v1s. Wingers Yamal/Williams cut inside to shoot or feed the striker.",
        "set_pieces": "Short corner option. Low delivery to the edge of the six-yard box for a tap-in.",
    },
    "Portugal": {
        "philosophy": "Ronaldo leads the line — every attack must end with him in a shooting position or heading a cross.",
        "shoot_rule": "Ronaldo shoots on sight inside 30m — headers, volleys, free kicks. Bruno shoots from 20-25m. Others pass to Ronaldo.",
        "pass_rule": "Wide to Bruno or the wingers, then a driven cross or cutback to Ronaldo at the back post or penalty spot.",
        "press_rule": "Moderate press — stay compact and let the midfield screen. Recover shape quickly.",
        "width_rule": "Wide players deliver quickly. Ronaldo attacks the back post. Bruno arrives late from midfield.",
        "set_pieces": "Free kicks are Ronaldo / Bruno territory — shoot direct or float to Ronaldo in the box.",
    },
    "Netherlands": {
        "philosophy": "Total football — every player attacks and defends. High press, overlapping fullbacks, shots from range.",
        "shoot_rule": "Shoot from range if the keeper is off their line. Inside the box shoot on first touch. Do not overelaborate.",
        "pass_rule": "Overload one side then switch quickly to the open fullback. Two passes in the box max before shooting.",
        "press_rule": "High press all over the pitch. Win the second ball and immediately play forward.",
        "width_rule": "Dumfries and Blind/Blind push to the byline. Inside forwards cut in and shoot.",
        "set_pieces": "Outswinging delivery to Van Dijk or the back-post header. Runner from outside the box for the second ball.",
    },
    "USA": {
        "philosophy": "Athletic, high-energy counter-pressing. Win the ball and transition quickly before the defense sets.",
        "shoot_rule": "Shoot inside 20m on the break. Pulisic and Reyna shoot when cutting inside. Do not wait for the perfect chance.",
        "pass_rule": "Direct transition ball — two or three passes max from winning possession to a shot attempt.",
        "press_rule": "Relentless high press. Every player presses immediately. Win the ball high up the pitch.",
        "width_rule": "Pulisic drives the left channel. Dest overlaps on the right. Early low cross into the box.",
        "set_pieces": "Driven delivery to the near post flick-on. Second runner at far post.",
    },
    "Croatia": {
        "philosophy": "Patient, technically excellent midfield control. Modric dictates tempo then releases runners.",
        "shoot_rule": "Shoot inside 22m with conviction. Modric and Kovacic shoot from range when a lane opens.",
        "pass_rule": "Modric controls tempo — short passes to maintain shape, then a killer ball in behind when the gap appears.",
        "press_rule": "Compact mid-block. Press selectively when the opponent is under pressure near the touchline.",
        "width_rule": "Wide midfielders overlap to deliver crosses. Strikers attack the near post.",
        "set_pieces": "Modric-delivered set piece — driven, low cross to the six-yard box.",
    },
    "Morocco": {
        "philosophy": "Defensive shape first, ruthless on the counter. Hard to beat, dangerous on the break.",
        "shoot_rule": "Shoot immediately on the counter inside 25m. Ziyech shoots from range. Do not slow the counter down.",
        "pass_rule": "Quick direct ball to the striker or wide man on the counter. Exploit space behind a high defensive line.",
        "press_rule": "Deep defensive block. Stay compact. Press high only when the opportunity is perfect.",
        "width_rule": "Ziyech and Boufal wide — drive at the fullback on the counter. Cross early.",
        "set_pieces": "Near-post delivery for the first header. Strong aerial threat from En-Nesyri.",
    },
    "Japan": {
        "philosophy": "Disciplined, organised, quick transitions. Compact defense, sharp counter-attacks.",
        "shoot_rule": "Shoot on sight inside 20m on the counter. Use pace to get into shooting positions quickly.",
        "pass_rule": "Fast, incisive passing on the transition. Two or three passes from winning the ball to a shot.",
        "press_rule": "High-intensity press as a unit. Disrupt the opponent's build-up early.",
        "width_rule": "Wide players run in behind on the counter. Early cross or cut inside to shoot.",
        "set_pieces": "Near-post delivery. Compact corner routines.",
    },
    "Mexico": {
        "philosophy": "Technical, combination football with flair. Build through midfield and use width.",
        "shoot_rule": "Shoot inside 22m. Lozano and Vega shoot when cutting inside from wide.",
        "pass_rule": "Combination play through midfield. One-twos around the box to create the shooting lane.",
        "press_rule": "Press in the middle third. Force mistakes and transition quickly.",
        "width_rule": "Lozano and Vega run at fullbacks. Layoff to the arriving midfielder for a shot.",
        "set_pieces": "Whipped delivery to the far post. Runner from deep.",
    },
    "Senegal": {
        "philosophy": "Physical, direct, and pacy. Use Mané's runs and pace to punish high defensive lines.",
        "shoot_rule": "Mané shoots on sight inside 25m. Forwards shoot first touch inside the box.",
        "pass_rule": "Direct ball over the top for Mané or through the channel. Do not overpass.",
        "press_rule": "High physical press. Win the second ball and go direct.",
        "width_rule": "Mané runs the left channel at pace. Right side delivers early crosses.",
        "set_pieces": "Aerial delivery to tall forwards and center-backs joining the attack.",
    },
    "Belgium": {
        "philosophy": "Use world-class individuals — De Bruyne's vision, Lukaku's strength, Carrasco's pace — to break teams open.",
        "shoot_rule": "De Bruyne shoots from 20-28m when the lane opens. Lukaku shoots on first touch inside the box. Don't wait.",
        "pass_rule": "De Bruyne dictates — short to feet then a sharp through ball in behind. Release Lukaku early.",
        "press_rule": "Mid-block, then press aggressively when the opponent plays into midfield. Quick transition.",
        "width_rule": "Carrasco and Meunier push wide. Early low cross or cutback to Lukaku at the penalty spot.",
        "set_pieces": "De Bruyne delivers. Lukaku and Vertonghen attack the back post for headers.",
    },
    "Canada": {
        "philosophy": "Energetic, athletic pressing football. Use Davies's pace on the left to destroy fullbacks.",
        "shoot_rule": "Davies and David shoot on sight inside 22m. Forwards shoot on first touch — don't overhold.",
        "pass_rule": "Direct ball over the top for Davies's run. Quick transition from midfield.",
        "press_rule": "Intense high press — all forwards press immediately. Win the ball in the opponent's half.",
        "width_rule": "Davies sprints the left channel relentlessly. Buckets cross early before the defense sets.",
        "set_pieces": "Driven delivery into the six-yard box. Milan or Laryea attack the near post.",
    },
    "South Korea": {
        "philosophy": "Disciplined defensive structure, rapid counter-attacks, and Son's creative runs.",
        "shoot_rule": "Son shoots on sight from anywhere inside 25m — he has the quality. Others shoot inside 18m only.",
        "pass_rule": "Quick direct pass to Son in behind. Support runs from midfield. Two or three passes to the shot.",
        "press_rule": "Compact 4-4-2 block. Press high when Son is near the opponent's defensive line.",
        "width_rule": "Son runs the left channel at pace. Right side plays more conservatively and supports.",
        "set_pieces": "Outswinging corner to Son arriving at the back post. Accurate delivery.",
    },
    "Uruguay": {
        "philosophy": "Garra charrúa — fight for every ball, defensive discipline, and lethal set pieces.",
        "shoot_rule": "Suárez and Núñez shoot inside 20m. Valverde shoots from range when arriving late. Be ruthless.",
        "pass_rule": "Hard-working midfield to protect then release Suárez or Núñez quickly on the break.",
        "press_rule": "Aggressive pressing all over the pitch. Win second balls. Make it physical and uncomfortable.",
        "width_rule": "Narrow shape — attack through the center. Wide players support and deliver set pieces.",
        "set_pieces": "Dead-ball specialists. Suárez attacks the near post, Godín or Giménez attacks the back post.",
    },
    "Colombia": {
        "philosophy": "Technical, creative football through James and Cuadrado. Flair with defensive solidity.",
        "shoot_rule": "James shoots from 20-25m — he has the technique. Falcao and forwards shoot on first touch in the box.",
        "pass_rule": "James controls the tempo — creative through balls and switches of play. Release wide players.",
        "press_rule": "Press in the middle third. Recover shape quickly. Don't leave gaps behind.",
        "width_rule": "Cuadrado dribbles at fullbacks on the right. James switches play to exploit space.",
        "set_pieces": "James delivers. Aerial threat from Mina and Falcao attacking the back post.",
    },
    "Denmark": {
        "philosophy": "Organised, hard-working, and efficient. Eriksen creates — the team finishes.",
        "shoot_rule": "Eriksen shoots from 22m when the lane opens. Forwards shoot first touch. Efficiency over flair.",
        "pass_rule": "Eriksen dictates — quick passes to maintain shape, then a killer ball or a shot.",
        "press_rule": "Disciplined pressing as a compact unit. Win the ball and play through Eriksen.",
        "width_rule": "Fullbacks push high to overlap. Wide midfielders cut inside to shoot or assist.",
        "set_pieces": "Eriksen delivers — pinpoint corners and free kicks. Kjær attacks the back post.",
    },
    "Switzerland": {
        "philosophy": "Tactical discipline, defensive shape, and dangerous on the break through Shaqiri.",
        "shoot_rule": "Shaqiri shoots from range if clear. Forwards shoot on first touch inside 18m. Disciplined finishing.",
        "pass_rule": "Compact and patient — pass through midfield then release Shaqiri or the striker on the break.",
        "press_rule": "Sit in a mid-block. Press in pairs when the opponent plays into tight spaces.",
        "width_rule": "Shaqiri uses his dribbling on the right to create. Left side more defensive.",
        "set_pieces": "Shaqiri delivers — accurate inswinging cross to the near or back post.",
    },
    "Austria": {
        "philosophy": "Aggressive gegenpressing and vertical, direct football. Win the ball and attack quickly.",
        "shoot_rule": "Arnautovic shoots inside 20m immediately. Midfielders shoot arriving late from 22m.",
        "pass_rule": "Vertical passes through the lines quickly. Two or three passes from winning ball to shot.",
        "press_rule": "Intense gegenpressing — win the ball back immediately in the middle third.",
        "width_rule": "Wide midfielders press high and deliver crosses. Fullbacks overlap when in possession.",
        "set_pieces": "Delivered to Arnautovic or Alaba arriving from midfield. Near-post danger.",
    },
    "Poland": {
        "philosophy": "Structured football built around Lewandowski's finishing. Get the ball to him in the box.",
        "shoot_rule": "Lewandowski shoots on sight inside 25m — always. Any other forward shoots inside 18m only.",
        "pass_rule": "Patient possession until a channel opens to feed Lewandowski. One direct pass into feet or space.",
        "press_rule": "Organised mid-block. Compact defensive shape behind the ball. Counter through Lewandowski.",
        "width_rule": "Wide players deliver early crosses to Lewandowski. He's the aerial and technical target.",
        "set_pieces": "Driven cross to Lewandowski at the back post. He will score from this.",
    },
    "Serbia": {
        "philosophy": "Physical, direct, set-piece oriented. Mitrovic in the box is the target for everything.",
        "shoot_rule": "Mitrovic shoots on first touch inside the box — always. Others shoot inside 20m only.",
        "pass_rule": "Long balls and direct passes to Mitrovic. Work the wide areas to deliver crosses.",
        "press_rule": "Physical mid-block. Win second balls. Make the game physical and press hard.",
        "width_rule": "Wide midfielders deliver crosses to Mitrovic. He wins everything in the air.",
        "set_pieces": "Every set piece targets Mitrovic. He is the most dangerous aerial threat in the tournament.",
    },
    "Turkey": {
        "philosophy": "Unpredictable and attacking. Use Calhanoglu's creativity and pace on the break.",
        "shoot_rule": "Calhanoglu shoots from 20-25m when stepping forward. Forwards shoot first touch in the box.",
        "pass_rule": "Quick combinations through Calhanoglu. Release wide players to attack space.",
        "press_rule": "Press aggressively in the middle third. High energy and unpredictable shape.",
        "width_rule": "Wide attackers run at fullbacks. Yildiz and Kulusevski cut inside to shoot.",
        "set_pieces": "Calhanoglu delivers. Aerial threat from center-backs on corners.",
    },
    "Scotland": {
        "philosophy": "Hard-working, direct, and physical. Fight for every ball and make it difficult.",
        "shoot_rule": "McGinn and Adams shoot inside 20m. Don't overelaborate — shoot when the chance appears.",
        "pass_rule": "Direct ball to Robertson on the overlap or long ball to the striker. Keep it simple.",
        "press_rule": "High-energy press. Scotland beat teams with effort and intensity, not technical superiority.",
        "width_rule": "Robertson charges the left wing relentlessly. Early cross or cutback from the byline.",
        "set_pieces": "Inswinging delivery to the back post. Physical aerial duels — Scotland win their share.",
    },
    "Ecuador": {
        "philosophy": "Energetic, direct, and physical. Use Valencia's power and Caicedo's engine to dominate.",
        "shoot_rule": "Valencia shoots inside 18m on first touch — he's powerful and clinical. Others shoot inside 20m.",
        "pass_rule": "Direct balls to Valencia or through the channel for runners. Caicedo drives from midfield.",
        "press_rule": "High press and physical battles in midfield. Win the second ball.",
        "width_rule": "Wide midfielders overlap. Early low cross to Valencia at the penalty spot.",
        "set_pieces": "Delivery to Valencia or Hincapié at the back post. Physical aerial threat.",
    },
    "Nigeria": {
        "philosophy": "Pace, power, and Super Eagles flair. Attack down the flanks and score with individual brilliance.",
        "shoot_rule": "Osimhen shoots on first touch inside the box — he is world class. Lookman shoots cutting inside.",
        "pass_rule": "Release Osimhen in behind with a through ball. Wide players drive at the fullback.",
        "press_rule": "High press with athleticism. Nigeria win the ball through intensity and pace.",
        "width_rule": "Lookman and the wide forward run at defenders. Cross early for Osimhen.",
        "set_pieces": "Delivery to Osimhen at the back post. Iwobi and wide players attack the second ball.",
    },
    "Italy": {
        "philosophy": "Defensive solidity and clinical counter-attacking. Azzurri excellence — disciplined and lethal.",
        "shoot_rule": "Shoot inside 18m on the counter — be clinical. Verratti or Barella shoot from 20m if arriving late.",
        "pass_rule": "Patient buildup — pass to maintain possession then release the striker on the break.",
        "press_rule": "Compact defensive shape. Mid-block. Press to force mistakes then counter immediately.",
        "width_rule": "Fullbacks push high on the counter. Wide attackers cut inside to shoot.",
        "set_pieces": "Driven delivery to Bonucci or the striker. Italy score from dead balls.",
    },
    "Australia": {
        "philosophy": "Fighting spirit — the Socceroos never give up. Hard press, direct play, and set-piece danger.",
        "shoot_rule": "Duke and forwards shoot inside 20m. Shoot on first touch — Australia cannot afford to waste chances.",
        "pass_rule": "Direct to the striker or wide players. Quick transition from defending to attacking.",
        "press_rule": "High physical press. Win the ball high and transition immediately.",
        "width_rule": "Fullbacks overlap. Wide midfielders deliver early crosses to the striker.",
        "set_pieces": "Delivery to Duke or the center-back at the back post. Australia's set pieces are a weapon.",
    },
    "Ivory Coast": {
        "philosophy": "Explosive African football — pace, power, and individual flair in attack.",
        "shoot_rule": "Haller and forwards shoot first touch inside the box. Pepe and wide forwards shoot cutting inside.",
        "pass_rule": "Direct to the striker or wide attacker in space. Use pace to exploit gaps.",
        "press_rule": "High-energy press. Win the ball in the opponent's half with physical intensity.",
        "width_rule": "Pepe and wide forwards dribble at fullbacks relentlessly. Cross early for Haller.",
        "set_pieces": "Aerial delivery to Haller or the center-backs. Ivory Coast win aerial duels.",
    },
    "Romania": {
        "philosophy": "Disciplined, organised, and dangerous on the counter through quick transitions.",
        "shoot_rule": "Pușcaș and forwards shoot inside 20m. Marin shoots from range when stepping forward.",
        "pass_rule": "Compact shape then quick vertical pass on the counter. Don't overelaborate.",
        "press_rule": "Mid-block defensive shape. Press selectively in the middle third.",
        "width_rule": "Wide midfielders support and deliver crosses. Fullbacks cautious.",
        "set_pieces": "Driven corner to the back post. Physical challenge from center-backs.",
    },
    "Venezuela": {
        "philosophy": "Ambitious, technical South American football with energetic pressing.",
        "shoot_rule": "Soteldo and forwards shoot inside 20m. Attack with freedom — shoot when the chance appears.",
        "pass_rule": "Combination play through the middle inspired by South American tradition. Fluid movement.",
        "press_rule": "High press with enthusiasm. Win the ball and play quick football.",
        "width_rule": "Soteldo uses his low center of gravity and pace to dribble at defenders. Cross or shoot.",
        "set_pieces": "Delivery to the back post. Physical challenge from tall forwards.",
    },
    "Panama": {
        "philosophy": "Defensive first, competitive, and dangerous from set pieces. Never give up.",
        "shoot_rule": "Shoot inside 18m only — be clinical when the chance comes. Muñoz and Cox are the threats.",
        "pass_rule": "Organised build-up. Protect the ball and look for counterattacking opportunities.",
        "press_rule": "Deep defensive block. Stay compact. Win the ball and release quickly on the break.",
        "width_rule": "Muñoz overlaps on the right to deliver crosses. Set pieces are Panama's best weapon.",
        "set_pieces": "Whipped delivery for aerial duels. Panama score from corners and free kicks.",
    },
    "Egypt": {
        "philosophy": "Salah-centric — get the ball to Salah in space and let him decide the game.",
        "shoot_rule": "Salah shoots on sight inside 25m — anything, any angle. Others shoot inside 18m only.",
        "pass_rule": "Play to Salah's feet or in behind immediately. Everything goes through him.",
        "press_rule": "Moderate press. Protect defensive shape. Counter through Salah.",
        "width_rule": "Salah dominates the right and cuts inside. Left side supports and delivers for him.",
        "set_pieces": "Deliver to Salah arriving from deep or to El-Hadary for aerial threat.",
    },
    "Saudi Arabia": {
        "philosophy": "Organised, compact defending followed by quick transitions. Shock the bigger nations.",
        "shoot_rule": "Al-Dawsari shoots on sight inside 22m — he's capable of stunning goals. Others inside 18m.",
        "pass_rule": "Patient buildup then quick release to Al-Dawsari or the striker in space.",
        "press_rule": "Compact 4-5-1 defensive block. Press as a unit at the right moment.",
        "width_rule": "Al-Dawsari drives at the fullback from the left. Early cross or shot from a tight angle.",
        "set_pieces": "Organised routine. Target the back post for aerial challenge.",
    },
    "Honduras": {
        "philosophy": "Physical, hard-working Central American football. Fight for every inch.",
        "shoot_rule": "Shoot inside 18m when the chance arrives. Lozano type forwards shoot cutting inside.",
        "pass_rule": "Direct and physical play. Long balls and second balls. Win the physical battle.",
        "press_rule": "High physical press. Win the ball through effort and physicality.",
        "width_rule": "Wide midfielders run hard at defenders. Cross early for the striker.",
        "set_pieces": "Whipped delivery to the back post. Physical aerial challenge.",
    },
    "Jamaica": {
        "philosophy": "Reggae Boyz — athletic, pacy, and unpredictable. Use raw pace to hurt opponents.",
        "shoot_rule": "Antonio and forwards shoot inside 20m on first touch. Use pace to get into positions fast.",
        "pass_rule": "Direct ball over the top for the pacy forwards. Quick transition from midfield.",
        "press_rule": "High-energy athletic press. Win the ball with raw physicality and pace.",
        "width_rule": "Wide players sprint at fullbacks. Cross early or cut inside to shoot.",
        "set_pieces": "Delivery to Antonio at the back post. Physical aerial contest.",
    },
    "Cameroon": {
        "philosophy": "Indomitable Lions — physical, direct, athletic. Aboubakar leads the attack.",
        "shoot_rule": "Aboubakar shoots on first touch inside the box. Choupo-Moting and forwards shoot inside 20m.",
        "pass_rule": "Direct ball to Aboubakar or wide players. Use pace and power to break through.",
        "press_rule": "High physical press. Win the ball through raw athleticism and intensity.",
        "width_rule": "Wide forwards attack fullbacks with pace. Cross early for Aboubakar.",
        "set_pieces": "Delivery to Aboubakar at the back post. He wins headers.",
    },
    "Algeria": {
        "philosophy": "Flair and technique — Mahrez controls the game and creates from the right.",
        "shoot_rule": "Mahrez shoots cutting inside from the right inside 22m — always. Belaïli and forwards shoot inside 20m.",
        "pass_rule": "Mahrez controls the tempo. Through balls and dribbles to create chances for the striker.",
        "press_rule": "Moderate press. Recover shape quickly. Counter through Mahrez.",
        "width_rule": "Mahrez dominates the right and cuts inside to shoot or assist. Left side supports.",
        "set_pieces": "Mahrez delivers — whipped inswinger to the back post.",
    },
    "Tunisia": {
        "philosophy": "Organised, defensive, and dangerous on the break. Disciplined and compact.",
        "shoot_rule": "Khazri and forwards shoot inside 20m on the counter. Be clinical — chances are limited.",
        "pass_rule": "Patient possession. Quick direct ball on the break to the forwards.",
        "press_rule": "Compact defensive block. Difficult to break down. Counter quickly.",
        "width_rule": "Wide midfielders support and deliver crosses from deep. Set pieces are key.",
        "set_pieces": "Driven delivery for aerial contest. Meriah or the striker attacks the back post.",
    },
    "South Africa": {
        "philosophy": "Bafana Bafana — energetic, direct, and inspired by Percy Tau's creativity.",
        "shoot_rule": "Tau shoots inside 22m — he has the technique. Forwards shoot first touch inside the box.",
        "pass_rule": "Direct play to Tau or in behind for runners. Quick transition.",
        "press_rule": "High-energy press. Win the ball with physicality and pace.",
        "width_rule": "Tau and wide players attack the fullbacks. Cross early.",
        "set_pieces": "Delivery to the back post. Physical aerial contest.",
    },
    "Iran": {
        "philosophy": "Defensive discipline and dangerous set pieces. Taremi and Azmoun the attacking threats.",
        "shoot_rule": "Taremi shoots inside 20m — he's technically gifted. Azmoun shoots on first touch in the box.",
        "pass_rule": "Organised buildup through midfield. Release Taremi or Azmoun at the right moment.",
        "press_rule": "Compact defensive block. Difficult to break through. Counter on the break.",
        "width_rule": "Wide midfielders support and deliver set pieces. Iran exploit dead balls.",
        "set_pieces": "Iran are strong from dead balls — whipped delivery to Taremi or Hosseini at the back post.",
    },
    "Qatar": {
        "philosophy": "Home nation pride — Almoez Ali leads the attack with technical Al Annabi football.",
        "shoot_rule": "Almoez Ali shoots inside 20m immediately. Afif shoots from range on his stronger side.",
        "pass_rule": "Short technical passing in the Al Annabi style. Quick combinations to create space.",
        "press_rule": "Organised press as a compact unit. Protect the defensive shape.",
        "width_rule": "Afif and wide players run at defenders. Cross early for Almoez Ali.",
        "set_pieces": "Technical delivery for Almoez Ali and center-backs. Qatar's set pieces are organised.",
    },
    "China": {
        "philosophy": "Disciplined defensive organisation with quick counter-attacks.",
        "shoot_rule": "Wu Lei shoots inside 20m on the counter. Forwards shoot first touch — don't waste rare chances.",
        "pass_rule": "Patient defensive buildup then release Wu Lei or wide players quickly on the break.",
        "press_rule": "Deep defensive block. Stay compact. Press when the opponent makes a mistake.",
        "width_rule": "Wu Lei runs the left channel on the counter. Early cross from the right side.",
        "set_pieces": "Organised delivery to tall center-backs and forwards.",
    },
    "Iraq": {
        "philosophy": "Fighting spirit — organised defensive block and dangerous on set pieces.",
        "shoot_rule": "Al-Yasiri and forwards shoot inside 18m. Be clinical with the limited chances created.",
        "pass_rule": "Direct, simple football. Protect the ball and wait for the counterattacking moment.",
        "press_rule": "Compact 4-4-2 block. Win the ball in the middle third and counter.",
        "width_rule": "Wide midfielders work hard to deliver crosses. Physical contest in the box.",
        "set_pieces": "Whipped delivery to the back post. Iraq are competitive in the air from dead balls.",
    },
    "New Zealand": {
        "philosophy": "All Whites — never give up. Athletic, direct, and dangerous from set pieces.",
        "shoot_rule": "Wood and forwards shoot inside 18m immediately. Don't wait — chances are precious.",
        "pass_rule": "Direct to Wood or wide players. Long balls over the top on the counter.",
        "press_rule": "High-energy press with great work rate. Win the ball through effort.",
        "width_rule": "Wide players deliver crosses early for Wood's aerial ability.",
        "set_pieces": "Delivery to Wood at the back post — he is New Zealand's greatest weapon in the air.",
    },
    "Ghana": {
        "philosophy": "Black Stars — pace, power, and African flair. Ayew brothers lead the attack.",
        "shoot_rule": "André Ayew shoots inside 20m — he's the main threat. Jordan Ayew shoots cutting inside.",
        "pass_rule": "Direct to the Ayew brothers or wide players in space. Quick transitions.",
        "press_rule": "High-energy press with athleticism. Win the ball and go direct.",
        "width_rule": "Wide forwards run at fullbacks. Cross early for the striker or cut inside to shoot.",
        "set_pieces": "Delivery to the back post. Ayew and tall defenders attack aerial balls.",
    },
}

# Fallback for teams without a specific style
_DEFAULT_STYLE = {
    "philosophy": "Work hard as a team. Move the ball forward and shoot when in range.",
    "shoot_rule": "Shoot inside 22m without hesitation. Do not pass when you can shoot.",
    "pass_rule": "Move the ball forward with every pass. Never pass backward if a forward option exists.",
    "press_rule": "Press the ball when possession is lost. Win it back quickly.",
    "width_rule": "Use the wide players to stretch the defense. Deliver crosses into the box.",
    "set_pieces": "Deliver to the back post with a runner at the near post.",
}


def get_team_tactics(team_name: str) -> str:
    """
    Returns a formatted tactical brief for injection into every player's decision prompt.
    """
    style = TACTICAL_STYLES.get(team_name, _DEFAULT_STYLE)
    lines = [
        f"## {team_name.upper()} TEAM TACTICS",
        f"Philosophy : {style['philosophy']}",
        f"Shooting   : {style['shoot_rule']}",
        f"Passing    : {style['pass_rule']}",
        f"Pressing   : {style['press_rule']}",
        f"Width      : {style['width_rule']}",
        f"Set pieces : {style['set_pieces']}",
        "",
        "Follow these team rules on every decision. Your individual skill executes the team plan.",
    ]
    return "\n".join(lines)


# --- backfilled 2026 qualifiers (real squads; appended programmatically) ---
TACTICAL_STYLES['Norway'] = {
    'philosophy': 'Direct, powerful, vertical football built around Erling Haaland. Get the ball forward fast for Haaland to run onto, with Odegaard pulling the strings and pace out wide via Nusa and Bobb.',
    'shoot_rule': 'Haaland shoots on sight inside the box. Sorloth attacks crosses. Odegaard and wide men shoot from 20-22m when the lane opens.',
    'pass_rule': 'Progress quickly and feed Haaland early; vertical balls in behind for Haaland and the wingers. Odegaard dictates tempo from the half-spaces.',
    'press_rule': 'Aggressive front press from the forwards, then a compact mid-block. Win it high and attack the space immediately.',
    'width_rule': 'Wide and stretched: wingers hug the touchline, full-backs (Ryerson) overlap to deliver early crosses for Haaland.',
    'set_pieces': 'Major aerial threat - Haaland, Sorloth and the centre-backs attack every delivery; Odegaard takes corners and free-kicks.',
}
TACTICAL_STYLES['Sweden'] = {
    'philosophy': 'Organised and balanced under Graham Potter. Defend in a solid block, control through midfield, and strike fast through Isak and Gyokeres in transition.',
    'shoot_rule': 'Isak and Gyokeres shoot inside the box; Kulusevski and Forsberg shoot from the edge when they cut inside.',
    'pass_rule': 'Patient build-up through Svanberg and Cajuste, then quick vertical balls to release Isak, Gyokeres and Elanga in behind.',
    'press_rule': "Controlled mid-block; press in triggers when the ball goes wide or backwards. Stay compact, don't over-commit.",
    'width_rule': 'Balanced width: Kulusevski and Elanga provide the outlets, full-backs support rather than bomb forward.',
    'set_pieces': 'Forsberg delivers; Lindelof, Hien and Gyokeres are aerial targets. Strong defensively on set pieces.',
}
TACTICAL_STYLES['Bosnia and Herzegovina'] = {
    'philosophy': 'Possession-leaning and physical, built around the experience of Edin Dzeko up front and a hard-working midfield.',
    'shoot_rule': 'Dzeko and Demirovic shoot inside the box; Tabakovic attacks crosses. Midfielders shoot from distance sparingly.',
    'pass_rule': 'Build through Tahirovic and Hadziahmetovic, work it to the front men early, and use Dzeko as a hold-up reference point.',
    'press_rule': 'Moderate mid-block press; squeeze centrally and force play wide, then win second balls.',
    'width_rule': 'Dedic and Kolasinac provide width from full-back; wingers tuck inside to support the strikers.',
    'set_pieces': 'Strong aerial threat through Dzeko, Demirovic and the centre-backs; a key source of goals.',
}
TACTICAL_STYLES['DR Congo'] = {
    'philosophy': 'Athletic, aggressive and quick in transition. Win the ball high and attack at pace through powerful, technical forwards.',
    'shoot_rule': 'Wissa, Bakambu and Mayele shoot inside the box; Bongonda and Kakuta strike from the edge.',
    'pass_rule': 'Fast vertical transitions - release Wissa and Bongonda in behind. Mbemba and Wan-Bissaka start moves from the back.',
    'press_rule': 'High, aggressive press from an athletic front line; aim to turn defences over in their own half.',
    'width_rule': 'Wide and direct: wingers run in behind, Wan-Bissaka and Masuaku overlap.',
    'set_pieces': 'Mbemba and the forwards are aerial threats; Kakuta delivers set pieces.',
}
TACTICAL_STYLES['Cape Verde'] = {
    'philosophy': 'Compact, organised and technical. Defend as a unit and counter quickly through pacey, skilful wide players.',
    'shoot_rule': 'Garry Rodrigues, Jovane Cabral and Ryan Mendes shoot from wide and the edge; strikers finish inside the box.',
    'pass_rule': 'Stay compact, then break at speed - quick combinations and balls in behind for the wide forwards.',
    'press_rule': 'Disciplined mid-to-low block; press selectively and protect the centre.',
    'width_rule': 'Width from the wingers who cut inside; full-backs support rather than overlap aggressively.',
    'set_pieces': 'Logan Costa is an aerial threat; well-organised defensively on set pieces.',
}
TACTICAL_STYLES['Curacao'] = {
    'philosophy': 'Pragmatic and well-drilled under Dick Advocaat. Sit in a compact block, stay disciplined, and counter through quick, technical attackers.',
    'shoot_rule': 'Locadia and the strikers finish inside the box; Chong and Kuwas shoot from the edge cutting in.',
    'pass_rule': 'Win it and break quickly through Chong and Hansen; Bazoer organises and progresses from deep.',
    'press_rule': 'Compact low-to-mid block; stay organised and spring on transitions rather than pressing high.',
    'width_rule': 'Wingers provide the outlets on the break; full-backs stay disciplined.',
    'set_pieces': 'Bazoer and the taller players attack deliveries; sound defensively.',
}
TACTICAL_STYLES['Jordan'] = {
    'philosophy': 'Disciplined, hard-working and counter-attacking. Defend deep in numbers and hit teams through the pace of Musa Al-Taamari.',
    'shoot_rule': 'Olwan finishes inside the box; Al-Taamari cuts in and shoots; midfielders shoot from distance rarely.',
    'pass_rule': 'Absorb pressure, then break fast and feed Al-Taamari in space; keep it simple and compact in your own half.',
    'press_rule': 'Low block, conservative pressing; stay compact and deny central space.',
    'width_rule': 'Al-Taamari provides the wide threat; full-backs stay home and defend first.',
    'set_pieces': 'Set pieces are a key scoring source; deliveries aimed at the centre-backs and Olwan.',
}
TACTICAL_STYLES['Haiti'] = {
    'philosophy': 'Athletic, direct and quick in transition under Sebastien Migne. Defend with energy and break at speed through powerful runners.',
    'shoot_rule': 'Pierrot, Isidor and Nazon finish inside the box; Bellegarde and Etienne shoot from the edge.',
    'pass_rule': 'Quick vertical transitions - get Bellegarde and Jean Jacques driving forward and release the strikers early.',
    'press_rule': 'Energetic pressing in spells; aim to win the ball and counter immediately.',
    'width_rule': 'Etienne and the wide men stretch play and run in behind; direct and vertical.',
    'set_pieces': 'Pierrot and the centre-backs are aerial targets; a useful set-piece threat.',
}
TACTICAL_STYLES['Uzbekistan'] = {
    'philosophy': 'Organised and solid under Fabio Cannavaro. Defend as a disciplined unit around Khusanov, then build patiently and create through Fayzullaev.',
    'shoot_rule': 'Shomurodov and Sergeev finish inside the box; Fayzullaev and Masharipov shoot from the edge.',
    'pass_rule': 'Patient, controlled build-up; work it to Fayzullaev and Masharipov to unlock defences, with balls in behind for Shomurodov.',
    'press_rule': 'Compact, well-drilled mid-block; press in coordinated triggers, stay organised.',
    'width_rule': 'Balanced width; wingers support Shomurodov, full-backs join selectively.',
    'set_pieces': 'Khusanov and the taller players attack deliveries; strong and organised defensively.',
}
